### ISSUE TITLE
请问支持下载oedrive中文件吗？

### ISSUE THREAD

**Issue by dzhl** [gaowanliang/LightUploader#10]
请问支持下载onedrive中文件吗？我需要可以同时支持上传和下载，目前在用rlcone，感觉连接onedrive没有这个快。

**Comment by gaowanliang** [comment]
目前没有支持任何平台下载的计划

**Comment by dzhl** [comment]
> 目前没有支持任何平台下载的计划

好可惜，网上找到的除了rlone外基本都只是有上传功能，没有下载功能，估计不好实现吧

**Comment by gaowanliang** [comment]
很好实现，但实际上在不挂载的情况下在控制台中下载文件其实是伪需求，我有一万种方法把文件从OneDrive中直接下载到远程机器，但是几乎很难有方法直接在命令行里上传。正是这种下载容易而上传很难，才导致现在的情况，大多数人做上传而忽略了下载，因为下载实在是太简单了

**Comment by dzhl** [comment]
> 很好实现，但实际上在不挂载的情况下在控制台中下载文件其实是伪需求，我有一万种方法把文件从OneDrive中直接下载到远程机器，但是几乎很难有方法直接在命令行里上传。正是这种下载容易而上传很难，才导致现在的情况，大多数人做上传而忽略了下载，因为下载实在是太简单了

哦，是这样啊。我在世纪互联里有个文件夹需要下载，这个文件夹不对外分享，请问我在命令行里改怎么实现下载呢？

**Comment by dzhl** [comment]
> 参考 https://gwliang.com/2020/05/26/linux-control-download-onedrive-files/

以前看过了，不过还是不方便，算了，我还是老老实实使用rclone吧。我是相每天同步上传下载同一份文件，带cook整的有些麻烦了
