### ISSUE TITLE
关于Google Driver上传的两个问题

### ISSUE THREAD

**Issue by MorningP** [gaowanliang/LightUploader#13]
我根据您博客上的文章进行设置，成功设置了Google Driver的配置文件并且使用命令成功进行了手动上传，非常感谢您，但是在上传过程中出现了一些令人不悦的小问题，在这里想请问一下。
1.在上传时，无法使用-r参数设置上传的目录，只能上传至根目录，我不太清楚这个是不是目前的限制。
2.在上传时，除了上传我所需要的文件，另外它（Download bot）还在我Google Driver的根目录建立了一个同名文件夹。
3.我注意到您博客上的文章中使用“”将上传的文件和目标目录包覆了起来，我不太明白这样做的必要性，因为我尝试过不使用“”，发现也是同样可以使用的。

最后附上为数不多的日志：/root/LightUploader -c xxxx.json -f "/path/bakfile" -r "/backup"
`/path/bakfile` 开始上传，大小: `xx KB`2021/09/27 22:28:42 /bakfile /root /path
`bakfile开始上传至Google Drive

**Comment by gaowanliang** [comment]
1. 对于Google Drive `-r` 是不能使用的，这个不算是什么大问题，我老是忘了修，不过目前准备考研中，没时间处理这些问题
2. 文件夹问题我有时间再去详细的排查一下，只要不是影响使用的恶性bug，这几个月内都不再做处理
3. 引号包裹是个人习惯，与Linux/cmd的语法有关，防止在文件夹名出现空格时出现问题

**Comment by MorningP** [comment]
了解，感谢回复。
