### ISSUE TITLE
尝试授权时提示报错

### ISSUE THREAD

**Issue by huankong233** [gaowanliang/LightUploader#15]
panic: runtime error: index out of range [1] with length 0

goroutine 1 [running]:
main/graph/net/http.getAccessToken(0x7ffdee3a283d, 0x3e, 0x0, 0xaba01c, 0x2, 0x0, 0x0)
        D:/program_data/go/LightUploader/graph/net/http/OAuth2.go:115 +0xc41
main/graph/net/http.NewPassCheck(0x7ffdee3a283d, 0x3e, 0x0, 0xaba01c, 0x2, 0x0, 0x0)
        D:/program_data/go/LightUploader/graph/net/http/OAuth2.go:42 +0x92
main.ApplyForNewPass(0x7ffdee3a283d, 0x3e, 0x0, 0x5f, 0x0)
        D:/program_data/go/LightUploader/main.go:32 +0x101
main.main()
        D:/program_data/go/LightUploader/main.go:403 +0xc0d

服务器是centos7

**Comment by gaowanliang** [comment]
可能是复制时有问题，亦或是链接有误，建议多次尝试，或将链接进行部分打码后上传，注意，每次申请的链接有效期只有10分钟，超时将无法使用

**Comment by huankong233** [comment]
后来已经知道问题了，好像是系统的问题，切换到debian即可正常工作

**Comment by huankong233** [comment]
后面我转用OneDriveUploader已经可以正常使用了
