### ISSUE TITLE
OD报错

### ISSUE THREAD

**Issue by taiyi747** [gaowanliang/LightUploader#4]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x95641b]

goroutine 1 [running]:
main.DirSize.func1(0x7ffd5e48483f, 0x8, 0x0, 0x0, 0xb93ac0, 0xc00030a210, 0xc000233a80, 0x43d0ce)
        D:/program_data/go/LightUploader/main.go:241 +0x2b
path/filepath.Walk(0x7ffd5e48483f, 0x8, 0xc000233a98, 0xc000233aa8, 0x768afa)
        D:/program_app/go/src/path/filepath/path.go:404 +0x6a
main.DirSize(0x7ffd5e48483f, 0x8, 0xfcb820, 0x0, 0x0)
        D:/program_data/go/LightUploader/main.go:240 +0x66
main.main()
        D:/program_data/go/LightUploader/main.go:329 +0x107d

**Comment by taiyi747** [comment]
是不是我安装错了，ubuntu16.04

**Comment by gaowanliang** [comment]
请告诉我您的具体操作，或者给出控制台操作截图

**Comment by taiyi747** [comment]
https://www.gejiba.com/view.php/89cbafdc52bb51990f57cb7c297132d7.png

**Comment by taiyi747** [comment]
上传文件夹貌似就出问题...

**Comment by gaowanliang** [comment]
我看了一下，是没有找到这个文件夹导致的

**Comment by gaowanliang** [comment]
我今天也遇到了这个问题，初步分析，是文件夹内的文件名不合法，或者是由程序生成的，（在Windows下）提示找不到路径，无法删除，导致程序返回了空值，稍后会发布一个版本帮助定位这个问题

**Comment by taiyi747** [comment]
我之前把线程拉到30，速度不到1000kb/s，换成rclone速度是2500-4000kb/s，貌似上传这块还需要改进，onedrive

**Comment by taiyi747** [comment]
> 我今天也遇到了这个问题，初步分析，是文件夹内的文件名不合法，或者是由程序生成的，（在Windows下）提示找不到路径，无法删除，导致程序返回了空值，稍后会发布一个版本帮助定位这个问题

还有一个情况下，没有这个文件夹也会出现这个问题

**Comment by gaowanliang** [comment]
不是线程越多上传速度越快，具体要看网络情况，和机器本身素质，二者用的API都是一样的。如果在设置正确的情况下，应该和rclone一样快，甚至是比rclone快才对。

至于你说的没有这个文件夹的情况，实际上是包含在我说的那个情况之中了，没有这个文件夹也是找不到路径。

**Comment by gaowanliang** [comment]
这个不是说是用脚本就可以试出来的，是要个人多次尝试总结出最适合自己vps的一套方案。包括线程的数量啊，分块的大小啊，甚至是超时的时间啊，都会影响上传的速度。这个需要大量且反复的尝试，不是说一个脚本装上就完事了。这个也与我当初设计这个东西的想法相悖，本身就是一个即装即用即走的东西。真要想长期用不如装一个rclone省心省力，本身人家已经做得足够好了，是碾压级的存在。
