### ISSUE TITLE
GD上传-r参数无效

### ISSUE THREAD

**Issue by madlaxcb** [gaowanliang/LightUploader#5]
LightUploader -c /root/XXX.json -f "download" -r "PTUPLOAD"

download直接上传在根目录了，在根目录新建了个PTUPLOAD后再执行也还是上传在根目录。

**Comment by gaowanliang** [comment]
目前GD为测试版，仅提供基本的上传功能，包括`-r`,`-to`,`-m`参数目前均不支持

**Comment by madlaxcb** [comment]
> 
> 
> 目前GD为测试版，仅提供基本的上传功能，包括`-r`,`-to`,`-m`参数目前均不支持

好的，期待后续完善。
