### ISSUE TITLE
同样上传出错

### ISSUE THREAD

**Issue by xiaoxinhuozhu** [gaowanliang/LightUploader#8]
cpu卡死后重启再上传显示：
2021/05/14 16:59:13 EOF
panic: EOF

goroutine 1 [running]:
log.Panicln(0xc00003fdc8, 0x1, 0x1)
        D:/program_app/go/src/log/log.go:365 +0xac
main.main()
        D:/program_data/go/onedrive/main.go:290 +0x1695

**Comment by gaowanliang** [comment]
麻烦上传一下授权文件中的内容，其中`RefreshToken`项和`Other`中的`access_token`，`refresh_token`，由于新网盘的加入，授权文件会发生变化，如果没有`Other`项，重新授权一下试试。

**Comment by xiaoxinhuozhu** [comment]
重新授权即可，谢谢！
